module.exports = {
  api: {
    // input: './src/api/RickAndMorty.yml',
    input: 'https://petstore.swagger.io/v2/swagger.json',
    output: {
      // target: './api/generated.ts',
      // schemas: './api/model',
      target: './src/api/rest',
      mode: 'tags-split',
      mock: true,
      prettier: true,

      override: {
        header: (): String[] => [`Generated by orval`, `Do not edit manually.`],
        mutator: {
          path: './src/helpers/axiosService.ts',
          name: 'customAxiosInstance',
        },
      },
    },
  },
};
