/**
 * Generated by orval
 * Do not edit manually.
 */
import type {EpisodeList, EpisodeGetParams} from '../theRickAndMorty.schemas';
import {
  customAxiosInstance,
  ErrorType,
  BodyType,
} from '../../helpers/axiosService';

export type AwaitedInput<T> = PromiseLike<T> | T;

export type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary List of episodes
 */
export const episodeGet = (params?: EpisodeGetParams, signal?: AbortSignal) => {
  return customAxiosInstance<EpisodeList>({
    url: `/episode`,
    method: 'get',
    signal,
    params,
  });
};
export type EpisodeGetResult = NonNullable<
  Awaited<ReturnType<typeof episodeGet>>
>;
