openapi: 3.0.1
info:
  title: The Rick and Morty
  description: rickandmortyapi.com
  version: 1.0.0
servers:
  - url: https://rickandmortyapi.com/api/
    description: Production server
  - url: https://stage.rickandmortyapi.com/api/
    description: Staging server
  - url: https://dev.rickandmortyapi.com/api/
    description: Develpment server
tags:
  - name: character
    description: Used to get all the characters.
  - name: episode
    description: Used to get all the episodes.

paths:
  /character:
    get:
      tags:
        - character
      summary: List of characters
      operationId: characterGet
      parameters:
        - name: page
          in: query
          description: number of page
          schema:
            type: integer
        - name: name
          in: query
          description: Filter by name
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterList'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'

  /episode:
    get:
      tags:
        - episode
      summary: List of episodes
      operationId: episodeGet
      parameters:
        - name: page
          in: query
          description: number of page
          schema:
            type: integer
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EpisodeList'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    ErrorModel:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
    Info:
      properties:
        count:
          type: integer
        pages:
          type: integer
    CharacterList:
      type: object
      properties:
        info:
          $ref: '#/components/schemas/Info'
        results:
          type: array
          items:
            $ref: '#/components/schemas/Character'
    EpisodeList:
      properties:
        info:
          $ref: '#/components/schemas/Info'
        results:
          type: array
          items:
            $ref: '#/components/schemas/Episode'
    Character:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
        species:
          type: string
        image:
          type: string
    Episode:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        air_date:
          type: string
        episode:
          type: string
